components:
  schemas:
    Config:
      description: |-
        A container for L1S configuration.
      type: object
      properties:
        links:
          description: |-
            Connection between ports within a switch.
          type: array
          items:
            $ref: '../link/link.yaml#/components/schemas/Link'
          x-field-uid: 1
        operation:
          description: |-
            Operation to Create or Delete Links
          type: string
          x-field-uid: 2
          default: CREATE
          x-enum:
            CREATE:
              x-field-uid: 1
            DELETE:
              x-field-uid: 2