openapi: 3.0.3
info:
  title: Open Traffic Generator L1S(Layer1Switch) Model API
  description: |-
    OTG L1S(Layer1Switch) Model
  version: 0.0.2
  contact:
    url: https://github.com/open-traffic-generator/l1s
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
- url: /
paths: {}
